- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_default_from_email: "openwisp2@openwisp2.mydomain.com"
    # in the playbook variables add:
    openwisp2_extra_django_settings_instructions:
      - |
        OPENWISP_MONITORING_MANAGEMENT_IP_ONLY = False
